// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type HlsJob struct {
	ID       string
	UploadId string
	Status   bool
}

type VideoJob struct {
	ID       string
	UploadId string
	Index    sql.NullInt32
}
