// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type HlsJob struct {
	ID       string
	UploadId string
	Status   bool
}

type VideoJob struct {
	ID       string
	UploadId string
	Index    int32
	Filename string
}
