// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const addVideoJob = `-- name: AddVideoJob :exec
INSERT INTO public."VideoJobs"(
	id, "uploadId", index)
	VALUES ($1, $2, $3)
`

type AddVideoJobParams struct {
	ID       string
	UploadId string
	Index    sql.NullInt32
}

func (q *Queries) AddVideoJob(ctx context.Context, arg AddVideoJobParams) error {
	_, err := q.db.ExecContext(ctx, addVideoJob, arg.ID, arg.UploadId, arg.Index)
	return err
}

const getAllVideoJobs = `-- name: GetAllVideoJobs :many


SELECT id, "uploadId", index
	FROM public."VideoJobs"
`

// database/query.sql
func (q *Queries) GetAllVideoJobs(ctx context.Context) ([]VideoJob, error) {
	rows, err := q.db.QueryContext(ctx, getAllVideoJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoJob
	for rows.Next() {
		var i VideoJob
		if err := rows.Scan(&i.ID, &i.UploadId, &i.Index); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
