// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const addHlsJob = `-- name: AddHlsJob :exec
INSERT INTO public."HlsJobs"(
	id, "uploadId", status)
	VALUES ($1, $2, $3)
`

type AddHlsJobParams struct {
	ID       string
	UploadId string
	Status   bool
}

func (q *Queries) AddHlsJob(ctx context.Context, arg AddHlsJobParams) error {
	_, err := q.db.ExecContext(ctx, addHlsJob, arg.ID, arg.UploadId, arg.Status)
	return err
}

const addVideoJob = `-- name: AddVideoJob :exec
INSERT INTO public."VideoJobs"(
	id, "uploadId", index)
	VALUES ($1, $2, $3)
`

type AddVideoJobParams struct {
	ID       string
	UploadId string
	Index    sql.NullInt32
}

func (q *Queries) AddVideoJob(ctx context.Context, arg AddVideoJobParams) error {
	_, err := q.db.ExecContext(ctx, addVideoJob, arg.ID, arg.UploadId, arg.Index)
	return err
}

const getAllVideoJobs = `-- name: GetAllVideoJobs :many

SELECT id, "uploadId", index
	FROM public."VideoJobs"
`

// database/query.sql
func (q *Queries) GetAllVideoJobs(ctx context.Context) ([]VideoJob, error) {
	rows, err := q.db.QueryContext(ctx, getAllVideoJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoJob
	for rows.Next() {
		var i VideoJob
		if err := rows.Scan(&i.ID, &i.UploadId, &i.Index); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestUploadedChunk = `-- name: GetLatestUploadedChunk :one
SELECT id, "uploadId", index 
FROM public."VideoJobs" 
WHERE "uploadId" = $1
ORDER BY index DESC
LIMIT 1
`

func (q *Queries) GetLatestUploadedChunk(ctx context.Context, uploadid string) (VideoJob, error) {
	row := q.db.QueryRowContext(ctx, getLatestUploadedChunk, uploadid)
	var i VideoJob
	err := row.Scan(&i.ID, &i.UploadId, &i.Index)
	return i, err
}

const updateHlsJobStatus = `-- name: UpdateHlsJobStatus :exec
UPDATE public."HlsJobs"
	SET status=$1
	WHERE "uploadId"=$2
`

type UpdateHlsJobStatusParams struct {
	Status   bool
	UploadId string
}

func (q *Queries) UpdateHlsJobStatus(ctx context.Context, arg UpdateHlsJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateHlsJobStatus, arg.Status, arg.UploadId)
	return err
}
